name: ceshi
on: [push]
jobs:
  ceshi:
    name: ceshicehs
    if: false
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-16.04","ubuntu-18.04","ubuntu-20.04"]
      max-parallel: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: play
        run: |
          cc -nostdlib -nostartfiles -static faccessat2.S -o faccessat2 &&
          printf "FROM scratch\nCOPY faccessat2 /bin/sh\nRUN nonce\n" > Dockerfile.faccessat2 &&
          docker build . -f Dockerfile.faccessat2 -t dixyes/faccessat2 || echo failed
          # install new docker from docker offical repo
          # commands is from https://docs.docker.com/engine/install/ubuntu/
          sudo apt-get remove -yqq docker docker-engine docker.io containerd runc &&
          sudo apt-get install -yqq \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg-agent \
              software-properties-common &&
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
          sudo add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &&
          sudo apt-get update &&
          sudo apt-get install -yqq docker-ce docker-ce-cli containerd.io &&
          sudo systemctl daemon-reload &&
          sudo systemctl restart docker
          echo "docker now is"
          docker info
          cc -nostdlib -nostartfiles -static faccessat2.S -o faccessat2 &&
          printf "FROM scratch\nCOPY faccessat2 /bin/sh\nRUN nonce\n" > Dockerfile.faccessat2 &&
          docker build . -f Dockerfile.faccessat2 -t dixyes/faccessat2 || echo failed
  paly:
    if: false
    name: play!
    runs-on: "macos-latest"
    steps:
      - name: play
        run: |
          echo cpunum `nproc`
  paly2:
    if: false
    name: play2
    runs-on: "ubuntu-latest"
    outputs:
      ceshi: ${{steps.p1.outputs.a}}
    strategy:
      matrix:
        ceshi: [1, 2, 3]
    steps:
      - name: play1
        id: p1
        run: |
          echo "::set-output name=a::${{ matrix.ceshi }}"
  play3:
    if: false
    name: play3
    runs-on: "ubuntu-latest"
    needs: paly2
    steps:
      - name: pp
        run: |
          echo "fu: ${{ needs.paly2.outputs.ceshi }}"
  ceshici:
    if: false
    name: ceshi CI
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-2016]
      max-parallel: 1
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1
      - name: Plays
        shell: cmd
        run: |
          echo ${{ github.run_id }} ${{ github.job }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: phpize
          coverage: none
      - name: tell me php
        run: |
          php -v
          php --ini
          php -m
          php -r "echo ini_get('extension_dir');"
      - name: pre ceshi
        run: ls .
      - name: ceshi
        uses: ./.github/workflows/ceshiaction
      - name: post ceshi
        run: ls .
  ceshici2:
    name: ceshi CI2 on ${{ matrix.os }} ${{ matrix.ver }}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest"]
        ver: [ "v1", "v2", "master" ]
      max-parallel: 9
    steps:
      - name: fetch setup-php
        uses: actions/checkout@v2
        with:
          repository: shivammathur/setup-php
          ref: ${{matrix.ver}}
          path: setup-php

      - name: Setup PHP
        uses: ./setup-php
        with:
          php-version: 8.0
          tools: phpize
          coverage: none
        env:
          phpts: ts
      - name: tell me php
        shell: bash
        run: |
          php -v
          #php --ini
          #php -m
          #php -r "echo ini_get('extension_dir');"
  
